# Generated by Django 5.2.7 on 2026-02-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("atendente", "Atendente"),
                    ("cliente", "Cliente"),
                ],
                default="cliente",
                max_length=20,
                verbose_name="Perfil",
            ),
        ),
    ]
