# Generated by Django 5.2.7 on 2026-02-14 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome/Razão Social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome Fantasia"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        help_text="Formato: XX.XXX.XXX/XXXX-XX",
                        max_length=18,
                        unique=True,
                        verbose_name="CNPJ",
                    ),
                ),
                (
                    "sistema_adquirido",
                    models.CharField(max_length=255, verbose_name="Sistema Adquirido"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail Principal"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                ("endereco", models.TextField(blank=True, verbose_name="Endereço")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientes_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientes_atualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nome"],
                "indexes": [
                    models.Index(fields=["cnpj"], name="clientes_cl_cnpj_db43af_idx"),
                    models.Index(fields=["nome"], name="clientes_cl_nome_b2cdde_idx"),
                    models.Index(
                        fields=["created_at"], name="clientes_cl_created_cc2563_idx"
                    ),
                ],
            },
        ),
    ]
