# Generated by Django 6.0.1 on 2026-02-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_rename_sistema_to_responsavel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="nome_responsavel",
            field=models.CharField(max_length=255, verbose_name="Nome do Responsável"),
        ),
    ]
