# Generated by Django 5.2.7 on 2026-02-05 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chamado",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chamados_criados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="chamado",
            name="status_kanban",
            field=models.CharField(
                choices=[
                    ("novo", "Novo"),
                    ("em_andamento", "Em Andamento"),
                    ("concluido", "Concluido"),
                ],
                default="novo",
                max_length=20,
                verbose_name="Status Kanban",
            ),
        ),
        migrations.AddField(
            model_name="chamado",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chamados_atualizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizado por",
            ),
        ),
        migrations.AddIndex(
            model_name="chamado",
            index=models.Index(
                fields=["status_kanban"], name="chamados_ch_status__30ac9f_idx"
            ),
        ),
    ]
