# Generated by Django 6.0.1 on 2026-02-06 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0002_chamado_created_by_chamado_status_kanban_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto_hash",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Hash do Texto",
                    ),
                ),
                (
                    "embedding_vector",
                    models.JSONField(verbose_name="Vetor de Embedding"),
                ),
                ("modelo", models.CharField(max_length=50, verbose_name="Modelo")),
                (
                    "uso_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Vezes Utilizado"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ultimo Uso"),
                ),
            ],
            options={
                "verbose_name": "Cache de Embedding",
                "verbose_name_plural": "Cache de Embeddings",
            },
        ),
        migrations.AddField(
            model_name="chamado",
            name="chamado_similar_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chamados_similares",
                to="chamados.chamado",
                verbose_name="Chamado Similar",
            ),
        ),
        migrations.AddField(
            model_name="chamado",
            name="ia_categoria",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Categoria IA"
            ),
        ),
        migrations.AddField(
            model_name="chamado",
            name="ia_confianca",
            field=models.FloatField(default=0.0, verbose_name="Confianca IA"),
        ),
        migrations.AddField(
            model_name="chamado",
            name="ia_palavras_chave",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Palavras-chave IA"
            ),
        ),
        migrations.AddField(
            model_name="chamado",
            name="ia_prioridade_sugerida",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Prioridade Sugerida IA"
            ),
        ),
        migrations.AddField(
            model_name="chamado",
            name="ia_problema_principal",
            field=models.TextField(blank=True, verbose_name="Problema Principal IA"),
        ),
        migrations.AddField(
            model_name="chamado",
            name="ia_processed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Processado IA em"
            ),
        ),
        migrations.AddField(
            model_name="chamado",
            name="ia_resumo",
            field=models.TextField(blank=True, verbose_name="Resumo IA"),
        ),
        migrations.AddField(
            model_name="chamado",
            name="is_recorrente",
            field=models.BooleanField(default=False, verbose_name="Chamado Recorrente"),
        ),
        migrations.AddField(
            model_name="chamado",
            name="similaridade_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Score de Similaridade"
            ),
        ),
        migrations.CreateModel(
            name="EmbeddingChamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding_vector",
                    models.JSONField(verbose_name="Vetor de Embedding"),
                ),
                ("texto_base", models.TextField(verbose_name="Texto Base")),
                (
                    "texto_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Hash do Texto"
                    ),
                ),
                ("modelo", models.CharField(max_length=50, verbose_name="Modelo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "chamado",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="chamados.chamado",
                        verbose_name="Chamado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Embedding Chamado",
                "verbose_name_plural": "Embeddings Chamados",
            },
        ),
    ]
