# Generated by Django 6.0.1 on 2026-02-15 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0003_embeddingcache_chamado_chamado_similar_ref_and_more"),
        ("clientes", "0003_add_cliente_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamado",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chamados",
                to="clientes.cliente",
                verbose_name="Cliente/Empresa",
            ),
        ),
    ]
