# Generated by Django 5.2.7 on 2026-02-15 01:20

import chamados.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0004_add_cliente_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anexochamado",
            name="arquivo",
            field=models.FileField(
                upload_to="chamados/anexos/%Y/%m/",
                validators=[chamados.validators.FileValidator()],
                verbose_name="Arquivo",
            ),
        ),
    ]
