# Generated by Django 6.0.1 on 2026-08-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_add_email_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIngestionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('encrypted_password', models.TextField(verbose_name='Senha Criptografada')),
                ('imap_host', models.CharField(default='imap.gmail.com', max_length=255, verbose_name='Servidor IMAP')),
                ('imap_port', models.PositiveIntegerField(default=993, verbose_name='Porta IMAP')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='Usar SSL')),
                ('folder', models.CharField(default='INBOX', max_length=100, verbose_name='Pasta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultima Verificacao')),
                ('last_error', models.TextField(blank=True, verbose_name='Ultimo Erro')),
                ('total_processed', models.PositiveIntegerField(default=0, verbose_name='Total de Chamados Criados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuracao de Email',
                'verbose_name_plural': 'Configuracoes de Email',
            },
        ),
    ]
