# Generated by Django 6.0.1 on 2026-08-26 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
        ('chamados', '0008_emailingestionconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='atendimento_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_gerados', to='atendimento.atendimento', verbose_name='Atendimento de origem'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='motivo_encaminhamento',
            field=models.TextField(blank=True, verbose_name='Motivo do encaminhamento'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='prioridade_calculada_atendimento',
            field=models.CharField(blank=True, help_text='Snapshot da prioridade (ex: P2) no momento da criacao do chamado -- nao muda retroativamente.', max_length=20, verbose_name='Prioridade calculada no atendimento'),
        ),
    ]
