# Generated by Django 6.0.1 on 2026-08-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_chamado_atendimento_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailingestionconfig',
            name='destino',
            field=models.CharField(choices=[('atendimento', 'Atendimento (fluxo completo com IA/AHP)'), ('chamado', 'Chamado (fluxo legado direto)')], default='atendimento', help_text='Define se o email recebido cria um Atendimento (fluxo com IA/AHP) ou um Chamado direto (legado).', max_length=20, verbose_name='Destino da ingestao'),
        ),
    ]
