# Generated by Django 6.0.1 on 2026-08-26 13:34

import chamados.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ahp', '0001_initial'),
        ('clientes', '0003_add_cliente_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status_atendimento', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_atendimento', 'Em Atendimento'), ('aguardando_cliente', 'Aguardando Cliente'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado'), ('encaminhado_para_chamado', 'Encaminhado para Chamado')], default='aguardando', max_length=30, verbose_name='Status do atendimento')),
                ('prioridade', models.CharField(choices=[('nao_classificado', 'Nao Classificado'), ('p1', 'P1 - Critica'), ('p2', 'P2 - Alta'), ('p3', 'P3 - Media'), ('p4', 'P4 - Baixa'), ('revisao_humana', 'Revisao Humana')], default='nao_classificado', max_length=20, verbose_name='Prioridade')),
                ('analise_ia_status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluida', 'Concluida'), ('erro', 'Erro')], default='pendente', max_length=15, verbose_name='Status da analise de IA')),
                ('indice_ahp', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Indice AHP')),
                ('regra_critica_confirmada', models.BooleanField(default=False, verbose_name='Regra critica confirmada')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='clientes.cliente', verbose_name='Cliente/Empresa')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('versao_ahp_utilizada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='ahp.versaoahp', verbose_name='Versao AHP utilizada')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='atendimento/anexos/%Y/%m/', validators=[chamados.validators.FileValidator()], verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('tipo_arquivo', models.CharField(choices=[('pdf', 'PDF'), ('imagem', 'Imagem'), ('documento', 'Documento'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Tipo')),
                ('tamanho', models.PositiveIntegerField(verbose_name='Tamanho (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME Type')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='atendimento.atendimento', verbose_name='Atendimento')),
            ],
            options={
                'verbose_name': 'Anexo de Atendimento',
                'verbose_name_plural': 'Anexos de Atendimento',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao_hierarquia', models.PositiveIntegerField(verbose_name='Versao da hierarquia')),
                ('versao_criterios', models.JSONField(blank=True, default=dict, verbose_name='Versao dos criterios')),
                ('versao_termos', models.JSONField(blank=True, default=dict, verbose_name='Versao dos termos')),
                ('versao_intensidades', models.JSONField(blank=True, default=dict, verbose_name='Versao das intensidades')),
                ('versao_matriz_criterios', models.JSONField(verbose_name='Matriz de criterios (congelada)')),
                ('versao_matriz_intensidades', models.JSONField(verbose_name='Matrizes de intensidades (congeladas)')),
                ('versao_faixas', models.JSONField(blank=True, default=dict, verbose_name='Faixas de tempo de espera')),
                ('pesos_criterios', models.JSONField(verbose_name='Pesos dos criterios')),
                ('lambda_max', models.FloatField(verbose_name='Lambda max')),
                ('ci', models.FloatField(verbose_name='CI')),
                ('ri', models.FloatField(verbose_name='RI')),
                ('cr', models.FloatField(verbose_name='CR')),
                ('prioridades_locais', models.JSONField(verbose_name='Prioridades locais (intensidades)')),
                ('intensidades', models.JSONField(verbose_name='Intensidades escolhidas')),
                ('contribuicoes', models.JSONField(verbose_name='Contribuicoes por criterio')),
                ('indice', models.FloatField(verbose_name='Indice')),
                ('prioridade', models.CharField(max_length=20, verbose_name='Prioridade')),
                ('classificacao_cor', models.CharField(max_length=7, verbose_name='Cor da classificacao')),
                ('regra_critica', models.BooleanField(default=False, verbose_name='Regra critica aplicada')),
                ('alteracoes_humanas', models.JSONField(blank=True, default=list, verbose_name='Alteracoes humanas')),
                ('erros', models.JSONField(blank=True, default=list, verbose_name='Erros')),
                ('modelo_deepseek', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo DeepSeek')),
                ('versao_prompt', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versao do prompt')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='atendimento.atendimento', verbose_name='Atendimento')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('versao_ahp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias', to='ahp.versaoahp', verbose_name='Versao AHP')),
            ],
            options={
                'verbose_name': 'Auditoria de Classificacao',
                'verbose_name_plural': 'Auditorias de Classificacao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoCriterioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('evidencia', models.TextField(blank=True, verbose_name='Evidencia')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('origem', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=20, verbose_name='Origem')),
                ('confianca', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Confianca')),
                ('dados_ausentes', models.BooleanField(default=False, verbose_name='Dados ausentes')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='atendimento.atendimento', verbose_name='Atendimento')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ahp.criterio', verbose_name='Criterio')),
                ('intensidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ahp.intensidade', verbose_name='Intensidade')),
            ],
            options={
                'verbose_name': 'Avaliacao de Criterio',
                'verbose_name_plural': 'Avaliacoes de Criterio',
                'ordering': ['atendimento', 'criterio__ordem'],
            },
        ),
        migrations.CreateModel(
            name='MensagemAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente_tipo', models.CharField(choices=[('cliente', 'Cliente'), ('atendente', 'Atendente'), ('sistema', 'Sistema')], max_length=15, verbose_name='Remetente')),
                ('conteudo', models.TextField(verbose_name='Conteudo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='atendimento.atendimento', verbose_name='Atendimento')),
            ],
            options={
                'verbose_name': 'Mensagem de Atendimento',
                'verbose_name_plural': 'Mensagens de Atendimento',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegraCriticaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('confirmada', models.BooleanField(default=False, verbose_name='Confirmada')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa')),
                ('origem', models.CharField(choices=[('manual', 'Manual')], default='manual', max_length=20, verbose_name='Origem')),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regra_critica', to='atendimento.atendimento', verbose_name='Atendimento')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('criterio_gatilho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ahp.criterio', verbose_name='Criterio gatilho')),
                ('termo_gatilho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ahp.termo', verbose_name='Termo gatilho')),
            ],
            options={
                'verbose_name': 'Regra Critica de Atendimento',
                'verbose_name_plural': 'Regras Criticas de Atendimento',
            },
        ),
        migrations.CreateModel(
            name='RevisaoHumanaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('prioridade_anterior', models.CharField(max_length=20, verbose_name='Prioridade anterior')),
                ('nova_prioridade', models.CharField(max_length=20, verbose_name='Nova prioridade')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisoes', to='atendimento.atendimento', verbose_name='Atendimento')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel')),
            ],
            options={
                'verbose_name': 'Revisao Humana de Atendimento',
                'verbose_name_plural': 'Revisoes Humanas de Atendimento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['status_atendimento'], name='atendimento_status__53cf80_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['prioridade'], name='atendimento_priorid_4a169f_idx'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['criado_em'], name='atendimento_criado__6125e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='avaliacaocriterioatendimento',
            constraint=models.UniqueConstraint(fields=('atendimento', 'criterio'), name='unique_avaliacao_por_atendimento_criterio'),
        ),
    ]
