# Generated by Django 6.0.1 on 2026-08-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaclassificacao',
            name='indice',
            field=models.FloatField(blank=True, help_text='Nulo quando a prioridade e REVISAO_HUMANA.', null=True, verbose_name='Indice'),
        ),
    ]
