# Generated by Django 6.0.1 on 2026-08-26 14:19

import atendimento.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_alter_auditoriaclassificacao_indice'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaclassificacao',
            name='auditoria_ia',
            field=models.JSONField(blank=True, default=dict, help_text='Saida do Agente 7 (checagens de consistencia), populado a partir da Fase 2.', verbose_name='Auditoria da IA'),
        ),
        migrations.AlterField(
            model_name='anexoatendimento',
            name='arquivo',
            field=models.FileField(upload_to='atendimento/anexos/%Y/%m/', validators=[atendimento.validators.AtendimentoFileValidator()], verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='avaliacaocriterioatendimento',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('agente_avaliacao', 'Agente 4 - Avaliacao de Criterios'), ('tempo_espera_service', 'WaitingTimeService (deterministico)')], default='manual', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='regracriticaatendimento',
            name='origem',
            field=models.CharField(choices=[('manual', 'Manual'), ('agente_validacao_critica', 'Agente 5 - Validacao Critica')], default='manual', max_length=30, verbose_name='Origem'),
        ),
    ]
