# Generated by Django 6.0.1 on 2026-08-26 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0003_auditoriaclassificacao_auditoria_ia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='assunto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Assunto'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='atendente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Atendente'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='email_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Message-ID do Email'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='origem',
            field=models.CharField(choices=[('chat', 'Chat'), ('email', 'E-mail')], default='chat', max_length=20, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='resumo',
            field=models.TextField(blank=True, verbose_name='Resumo'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='servico_afetado',
            field=models.CharField(blank=True, max_length=255, verbose_name='Servico afetado'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='session_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Prova de propriedade do atendimento para clientes anonimos -- nunca o pk numerico.', unique=True, verbose_name='Token de sessao (chat anonimo)'),
        ),
    ]
