# Generated by Django 4.2.3 on 2026-01-30 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protocolo",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Protocolo",
                    ),
                ),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("nota-fiscal", "Nota Fiscal"),
                            ("erro-sistema", "Erro no Sistema"),
                            ("financeiro", "Financeiro"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        max_length=50,
                        verbose_name="Tipo de Solicitacao",
                    ),
                ),
                ("assunto", models.CharField(max_length=255, verbose_name="Assunto")),
                ("descricao", models.TextField(verbose_name="Descricao")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("em_analise", "Em Analise"),
                            ("em_atendimento", "Em Atendimento"),
                            ("aguardando_cliente", "Aguardando Cliente"),
                            ("resolvido", "Resolvido"),
                            ("fechado", "Fechado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="aberto",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=20,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("landing_page", "Landing Page"),
                            ("chat", "Chat"),
                            ("email", "E-mail"),
                            ("telefone", "Telefone"),
                            ("dashboard", "Dashboard"),
                        ],
                        default="landing_page",
                        max_length=30,
                        verbose_name="Origem",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereco IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolvido em"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fechado em"
                    ),
                ),
                (
                    "chat_session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID Sessao Chat"
                    ),
                ),
                (
                    "ia_processed",
                    models.BooleanField(
                        default=False, verbose_name="Processado por IA"
                    ),
                ),
                (
                    "ia_response",
                    models.TextField(blank=True, verbose_name="Resposta IA"),
                ),
                (
                    "atendente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chamados_atendidos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atendente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chamados_abertos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chamado",
                "verbose_name_plural": "Chamados",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoChamado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo_acao",
                    models.CharField(
                        choices=[
                            ("criado", "Chamado Criado"),
                            ("status_alterado", "Status Alterado"),
                            ("atendente_atribuido", "Atendente Atribuido"),
                            ("comentario", "Comentario Adicionado"),
                            ("anexo_adicionado", "Anexo Adicionado"),
                            ("prioridade_alterada", "Prioridade Alterada"),
                            ("resposta_ia", "Resposta IA"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Acao",
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descricao")),
                (
                    "valor_anterior",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Valor Anterior"
                    ),
                ),
                (
                    "valor_novo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Valor Novo"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
                (
                    "chamado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="chamados.chamado",
                        verbose_name="Chamado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historico",
                "verbose_name_plural": "Historicos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComentarioChamado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("interno", "Interno (apenas equipe)"),
                            ("publico", "Publico (visivel ao cliente)"),
                            ("automatico", "Automatico (sistema/IA)"),
                        ],
                        default="publico",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("conteudo", models.TextField(verbose_name="Conteudo")),
                (
                    "autor_nome",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome do Autor"
                    ),
                ),
                (
                    "is_from_client",
                    models.BooleanField(default=False, verbose_name="Do Cliente"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "chamado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="chamados.chamado",
                        verbose_name="Chamado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario",
                "verbose_name_plural": "Comentarios",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnexoChamado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="chamados/anexos/%Y/%m/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "nome_original",
                    models.CharField(max_length=255, verbose_name="Nome Original"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("imagem", "Imagem"),
                            ("documento", "Documento"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "tamanho",
                    models.PositiveIntegerField(verbose_name="Tamanho (bytes)"),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME Type"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "chamado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="chamados.chamado",
                        verbose_name="Chamado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anexo",
                "verbose_name_plural": "Anexos",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chamado",
            index=models.Index(
                fields=["protocolo"], name="chamados_ch_protoco_70fcba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chamado",
            index=models.Index(fields=["email"], name="chamados_ch_email_5491aa_idx"),
        ),
        migrations.AddIndex(
            model_name="chamado",
            index=models.Index(fields=["status"], name="chamados_ch_status_f7e4eb_idx"),
        ),
        migrations.AddIndex(
            model_name="chamado",
            index=models.Index(
                fields=["created_at"], name="chamados_ch_created_8ea4df_idx"
            ),
        ),
    ]
