# Generated by Django 5.2.7 on 2026-02-15 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0005_alter_anexochamado_arquivo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "webhook_type",
                    models.CharField(
                        choices=[
                            ("discord", "Discord"),
                            ("slack", "Slack"),
                            ("custom", "Custom HTTP"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("encrypted_url", models.TextField(verbose_name="URL Criptografada")),
                (
                    "trigger_events",
                    models.JSONField(
                        default=list,
                        help_text="Lista de eventos que disparam o webhook: chamado_created, chamado_assigned, priority_urgent",
                        verbose_name="Eventos Gatilho",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "max_retries",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="Max Tentativas"
                    ),
                ),
                (
                    "total_sent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Enviados"
                    ),
                ),
                (
                    "total_success",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Sucesso"
                    ),
                ),
                (
                    "total_failed",
                    models.PositiveIntegerField(default=0, verbose_name="Total Falhas"),
                ),
                (
                    "last_triggered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ultimo Disparo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Configuracao de Webhook",
                "verbose_name_plural": "Configuracoes de Webhooks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("chamado_created", "Novo Chamado"),
                            ("chamado_assigned", "Chamado Atribuido"),
                            ("priority_urgent", "Prioridade Urgente"),
                            ("status_changed", "Status Alterado"),
                            ("new_comment", "Novo Comentario"),
                        ],
                        max_length=30,
                        verbose_name="Tipo",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titulo")),
                ("message", models.TextField(verbose_name="Mensagem")),
                ("is_read", models.BooleanField(default=False, verbose_name="Lida")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Lida em"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "chamado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="chamados.chamado",
                        verbose_name="Chamado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificacao",
                "verbose_name_plural": "Notificacoes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "created_at"],
                        name="chamados_no_user_id_3880ea_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="chamados_no_user_id_db7aa7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event", models.CharField(max_length=50, verbose_name="Evento")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Sucesso"),
                            ("failed", "Falha"),
                            ("retrying", "Tentando Novamente"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("payload_sent", models.JSONField(verbose_name="Payload Enviado")),
                (
                    "response_status_code",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="HTTP Status"
                    ),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, verbose_name="Resposta"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensagem de Erro"),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Tentativas"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "chamado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_logs",
                        to="chamados.chamado",
                        verbose_name="Chamado",
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="chamados.webhookconfig",
                        verbose_name="Webhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Webhook",
                "verbose_name_plural": "Logs de Webhooks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["webhook", "created_at"],
                        name="chamados_we_webhook_817ee7_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="chamados_we_status_216d3a_idx",
                    ),
                ],
            },
        ),
    ]
