# Generated by Django 6.0.1 on 2026-08-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0006_webhookconfig_notification_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='email_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Message-ID do Email'),
        ),
    ]
