# Generated by Django 6.0.1 on 2026-08-26 13:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('excluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Excluido em')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('orientacao', models.CharField(choices=[('positiva', 'Positiva (intensidade maior = maior prioridade)'), ('negativa', 'Negativa (intensidade maior = menor prioridade)')], default='positiva', max_length=10, verbose_name='Orientacao')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('importancia_negocio', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Importancia para o negocio')),
                ('regra_critica', models.BooleanField(default=False, help_text='Se este criterio pode disparar uma regra critica de seguranca.', verbose_name='Regra critica')),
                ('exige_revisao_humana', models.BooleanField(default=False, verbose_name='Exige revisao humana')),
                ('permite_deteccao_semantica', models.BooleanField(default=True, verbose_name='Permite deteccao semantica')),
                ('orientacoes_para_ia', models.TextField(blank=True, verbose_name='Orientacoes para a IA')),
                ('exemplos_positivos', models.TextField(blank=True, verbose_name='Exemplos positivos')),
                ('exemplos_negativos', models.TextField(blank=True, verbose_name='Exemplos negativos')),
                ('cor_identificacao', models.CharField(default='#64748B', max_length=7, validators=[django.core.validators.RegexValidator(message='Informe uma cor hexadecimal no formato #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor de identificacao')),
                ('icone', models.CharField(blank=True, max_length=100, verbose_name='Icone')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluido por')),
            ],
            options={
                'verbose_name': 'Criterio',
                'verbose_name_plural': 'Criterios',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Intensidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('excluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Excluido em')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('codigo', models.CharField(choices=[('ausente', 'Ausente'), ('muito_baixa', 'Muito Baixa'), ('baixa', 'Baixa'), ('moderada', 'Moderada'), ('alta', 'Alta'), ('critica', 'Critica'), ('inconclusiva', 'Inconclusiva')], max_length=20, verbose_name='Codigo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('orientacoes_para_ia', models.TextField(blank=True, verbose_name='Orientacoes para a IA')),
                ('exemplo_positivo', models.TextField(blank=True, verbose_name='Exemplo positivo')),
                ('exemplo_negativo', models.TextField(blank=True, verbose_name='Exemplo negativo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intensidades', to='ahp.criterio', verbose_name='Criterio')),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluido por')),
            ],
            options={
                'verbose_name': 'Intensidade',
                'verbose_name_plural': 'Intensidades',
                'ordering': ['criterio__ordem', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='FaixaTempoEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('minutos_min', models.PositiveIntegerField(verbose_name='Minutos (min)')),
                ('minutos_max', models.PositiveIntegerField(blank=True, help_text='Deixe em branco para uma faixa aberta (ex: mais de 60 minutos).', null=True, verbose_name='Minutos (max)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('criterio', models.ForeignKey(limit_choices_to={'codigo': 'TEMPO_DE_ESPERA'}, on_delete=django.db.models.deletion.CASCADE, related_name='faixas_tempo', to='ahp.criterio', verbose_name='Criterio')),
                ('intensidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faixas_tempo', to='ahp.intensidade', verbose_name='Intensidade')),
            ],
            options={
                'verbose_name': 'Faixa de Tempo de Espera',
                'verbose_name_plural': 'Faixas de Tempo de Espera',
                'ordering': ['criterio__ordem', 'ordem', 'minutos_min'],
            },
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('excluido_em', models.DateTimeField(blank=True, null=True, verbose_name='Excluido em')),
                ('termo', models.CharField(max_length=255, verbose_name='Termo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('tipo_correspondencia', models.CharField(choices=[('exato', 'Exato'), ('contem', 'Contem'), ('expressao', 'Expressao'), ('regex_segura', 'Regex Segura'), ('semantico', 'Semantico')], default='contem', max_length=20, verbose_name='Tipo de correspondencia')),
                ('exige_contexto', models.BooleanField(default=False, verbose_name='Exige contexto')),
                ('regra_critica', models.BooleanField(default=False, verbose_name='Regra critica')),
                ('considerar_mensagem_atual', models.BooleanField(default=True, verbose_name='Considerar mensagem atual')),
                ('considerar_historico', models.BooleanField(default=False, verbose_name='Considerar historico')),
                ('considerar_anexos', models.BooleanField(default=False, verbose_name='Considerar anexos')),
                ('considerar_imagens', models.BooleanField(default=False, verbose_name='Considerar imagens')),
                ('status_aprovacao', models.CharField(choices=[('pendente_aprovacao', 'Pendente de Aprovacao'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aprovado', max_length=20, verbose_name='Status de aprovacao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='ahp.criterio', verbose_name='Criterio')),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Excluido por')),
                ('intensidade_base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termos_base', to='ahp.intensidade', verbose_name='Intensidade base')),
            ],
            options={
                'verbose_name': 'Termo',
                'verbose_name_plural': 'Termos',
                'ordering': ['criterio__ordem', 'termo'],
            },
        ),
        migrations.CreateModel(
            name='VersaoAHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero_versao', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Numero da versao')),
                ('estado', models.CharField(choices=[('pendente_configuracao', 'Pendente de Configuracao'), ('rascunho', 'Rascunho'), ('processando', 'Processando'), ('valida', 'Valida'), ('inconsistente', 'Inconsistente'), ('ativa', 'Ativa'), ('arquivada', 'Arquivada'), ('erro', 'Erro')], default='rascunho', max_length=25, verbose_name='Estado')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('pesos_criterios', models.JSONField(blank=True, null=True, verbose_name='Pesos dos criterios')),
                ('lambda_max_criterios', models.FloatField(blank=True, null=True, verbose_name='Lambda max (criterios)')),
                ('ci_criterios', models.FloatField(blank=True, null=True, verbose_name='CI (criterios)')),
                ('cr_criterios', models.FloatField(blank=True, null=True, verbose_name='CR (criterios)')),
                ('prioridades_intensidades', models.JSONField(blank=True, null=True, verbose_name='Prioridades das intensidades')),
                ('lambda_max_intensidades', models.JSONField(blank=True, null=True, verbose_name='Lambda max (intensidades)')),
                ('ci_intensidades', models.JSONField(blank=True, null=True, verbose_name='CI (intensidades)')),
                ('cr_intensidades', models.JSONField(blank=True, null=True, verbose_name='CR (intensidades)')),
                ('p_max', models.FloatField(blank=True, null=True, verbose_name='P maximo')),
                ('ativada_em', models.DateTimeField(blank=True, null=True, verbose_name='Ativada em')),
                ('arquivada_em', models.DateTimeField(blank=True, null=True, verbose_name='Arquivada em')),
                ('mensagens_erro', models.JSONField(blank=True, default=list, verbose_name='Mensagens de erro')),
                ('ativada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ativada por')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Versao AHP',
                'verbose_name_plural': 'Versoes AHP',
                'ordering': ['-numero_versao'],
            },
        ),
        migrations.CreateModel(
            name='Comparacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('criterios', 'Criterios'), ('intensidades', 'Intensidades')], max_length=20, verbose_name='Tipo')),
                ('valor_saaty', models.FloatField(verbose_name='Valor (escala de Saaty)')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('criterio_coluna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ahp.criterio', verbose_name='Criterio (coluna)')),
                ('criterio_contexto', models.ForeignKey(blank=True, help_text='Preenchido apenas quando tipo=INTENSIDADES: qual criterio esta tendo suas intensidades comparadas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comparacoes_intensidade', to='ahp.criterio', verbose_name='Criterio de contexto')),
                ('criterio_linha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ahp.criterio', verbose_name='Criterio (linha)')),
                ('intensidade_coluna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ahp.intensidade', verbose_name='Intensidade (coluna)')),
                ('intensidade_linha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ahp.intensidade', verbose_name='Intensidade (linha)')),
                ('versao_ahp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparacoes', to='ahp.versaoahp', verbose_name='Versao AHP')),
            ],
            options={
                'verbose_name': 'Comparacao',
                'verbose_name_plural': 'Comparacoes',
                'ordering': ['versao_ahp', 'tipo', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='intensidade',
            constraint=models.UniqueConstraint(fields=('criterio', 'codigo'), name='unique_intensidade_por_criterio'),
        ),
        migrations.AddConstraint(
            model_name='versaoahp',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ativa')), fields=('estado',), name='unique_versao_ahp_ativa'),
        ),
        migrations.AddConstraint(
            model_name='comparacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('criterio_coluna__isnull', False), ('criterio_linha__isnull', False), ('intensidade_coluna__isnull', True), ('intensidade_linha__isnull', True), ('tipo', 'criterios')), models.Q(('criterio_coluna__isnull', True), ('criterio_contexto__isnull', False), ('criterio_linha__isnull', True), ('intensidade_coluna__isnull', False), ('intensidade_linha__isnull', False), ('tipo', 'intensidades')), _connector='OR'), name='comparacao_campos_consistentes_com_tipo'),
        ),
    ]
